title: WDW 2024
description: Sivako
permalink: /:slugified_categories/:title/
baseurl: /wdw2024

date_format: "%b %-d, %Y"

exclude:
  - "package*.json"
  - "*.config.js"
  - netlify.toml
  - README.md
  - LICENSE
  - Makefile
