title: WDW 2024
description: Sivako
permalink: /:slugified_categories/:title/
baseurl: /wdw2024

date_format: "%b %-d, %Y"

collections:
  pages:
    output: true
    permalink: /:path/

exclude:
  - "package*.json"
  - "*.config.js"
  - netlify.toml
  - README.md
  - LICENSE
  - Makefile
